dist: trusty
language: php

php:
  - 7.0
  - 7.1
  - 7.2
  - 7.4

before_script: 
  - composer install

script:
  - vendor/bin/phpunit

after_success:
  - travis_retry vendor/bin/php-coveralls

notifications:
  email: false
